FROM debian:bookworm-slim AS runtime

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash app
USER app
WORKDIR /app

# Copy pre-built binary and SQLX metadata
COPY target/release/api /usr/local/bin/api
COPY .sqlx .sqlx

ENTRYPOINT ["/usr/local/bin/api"]